# Generated by Django 3.0.4 on 2020-04-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpost',
            name='type',
            field=models.CharField(choices=[('post', 'Текст'), ('intro', '#intro'), ('link', 'Ссылка'), ('question', 'Вопрос'), ('pain', 'Расскажи где болит'), ('project', 'Проект'), ('referral', 'Рефералка'), ('battle', 'Батл'), ('weekly_digest', 'Еженедельный дайджест')], db_index=True, default='post', max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('post', 'Текст'), ('intro', '#intro'), ('link', 'Ссылка'), ('question', 'Вопрос'), ('pain', 'Расскажи где болит'), ('project', 'Проект'), ('referral', 'Рефералка'), ('battle', 'Батл'), ('weekly_digest', 'Еженедельный дайджест')], db_index=True, default='post', max_length=32),
        ),
    ]
