# Generated by Django 3.0.4 on 2020-04-21 07:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_email_unsubscribed'),
        ('posts', '0002_auto_20200418_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='postvote',
            name='ipaddress',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='postvote',
            name='useragent',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='postvote',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='posts.Post'),
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ipaddress', models.GenericIPAddressField(null=True)),
                ('useragent', models.CharField(max_length=512, null=True)),
                ('first_viewed_at', models.DateTimeField(auto_now_add=True)),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='posts.Post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_views', to='users.User')),
            ],
            options={
                'db_table': 'post_views',
                'unique_together': {('user', 'post')},
            },
        ),
    ]
