# Generated by Django 3.0.4 on 2020-04-21 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_email_unsubscribed'),
        ('posts', '0004_auto_20200421_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='users.User'),
        ),
    ]
