# Generated by Django 3.0.4 on 2020-04-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200426_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='chat_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='chat_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='chat_url',
            field=models.URLField(null=True),
        ),
    ]
