# Generated by Django 3.1 on 2020-08-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20200523_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpost',
            name='label',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalpost',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='label',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='metadata',
            field=models.JSONField(null=True),
        ),
    ]
