# Generated by Django 3.1 on 2020-08-22 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20200809_1616'),
        ('posts', '0012_postbookmark'),
    ]

    operations = [
    ]
