# Generated by Django 3.1 on 2020-10-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20200822_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='deleted_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='deleted_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
