# Generated by Django 3.1 on 2021-01-15 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200822_0818'),
        ('posts', '0016_auto_20201115_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_posts_from', to='posts.post')),
                ('post_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_posts_to', to='posts.post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_posts', to='users.user')),
            ],
            options={
                'db_table': 'linked_posts',
                'unique_together': {('post_from', 'post_to')},
            },
        ),
    ]
