# Generated by Django 3.2 on 2021-05-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_linkedpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpost',
            old_name='is_visible_on_main_page',
            new_name='is_visible_in_feeds',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='is_visible_on_main_page',
            new_name='is_visible_in_feeds',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='is_visible_on_main_page',
            new_name='is_visible_in_feeds',
        ),
        migrations.AlterField(
            model_name='historicalpost',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='linkedpost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
