# Generated by Django 3.2 on 2021-05-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20210527_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='label_code',
            field=models.CharField(db_index=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='label_code',
            field=models.CharField(db_index=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpost',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunSQL("""
            update posts set label_code = label->>'code' where label is not null
        """)
    ]
