# Generated by Django 3.2 on 2021-08-17 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20210528_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpost',
            name='label',
        ),
        migrations.RemoveField(
            model_name='post',
            name='label',
        ),
    ]
