# Generated by Django 3.2 on 2021-09-08 19:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20210817_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='coauthors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=list, size=None),
        ),
        migrations.AddField(
            model_name='post',
            name='coauthors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=list, size=None),
        ),
    ]
