# Generated by Django 3.2 on 2021-09-10 15:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0020_auto_20210817_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='coauthors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), db_index=True,
                                                            default=list, size=None),
        ),
        migrations.AddField(
            model_name='post',
            name='coauthors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), db_index=True,
                                                            default=list, size=None),
        ),
        migrations.AlterField(
            model_name='historicalpost',
            name='type',
            field=models.CharField(
                choices=[('post', 'Текст'), ('intro', '#intro'), ('link', 'Ссылка'), ('question', 'Вопрос'),
                         ('pain', 'Боль'), ('idea', 'Идея'), ('project', 'Проект'), ('event', 'Событие'),
                         ('referral', 'Рефералка'), ('battle', 'Батл'), ('weekly_digest', 'Журнал Клуба'),
                         ('guide', 'Путеводитель')], db_index=True, default='post', max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(
                choices=[('post', 'Текст'), ('intro', '#intro'), ('link', 'Ссылка'), ('question', 'Вопрос'),
                         ('pain', 'Боль'), ('idea', 'Идея'), ('project', 'Проект'), ('event', 'Событие'),
                         ('referral', 'Рефералка'), ('battle', 'Батл'), ('weekly_digest', 'Журнал Клуба'),
                         ('guide', 'Путеводитель')], db_index=True, default='post', max_length=32),
        ),
    ]
