# Generated by Django 3.2 on 2021-09-11 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20210910_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpost',
            name='is_approved_by_moderator',
        ),
        migrations.RemoveField(
            model_name='historicalpost',
            name='is_commentable',
        ),
        migrations.RemoveField(
            model_name='historicalpost',
            name='is_pinned_until',
        ),
        migrations.RemoveField(
            model_name='historicalpost',
            name='is_shadow_banned',
        ),
        migrations.RemoveField(
            model_name='historicalpost',
            name='is_visible_in_feeds',
        ),
        migrations.RemoveField(
            model_name='historicalpost',
            name='label_code',
        ),
        migrations.RemoveField(
            model_name='historicalpost',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='postview',
            name='useragent',
        ),
        migrations.RemoveField(
            model_name='postvote',
            name='useragent',
        ),
    ]
