# Generated by Django 3.2.5 on 2021-10-05 12:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_postsubscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='additional_chat_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=list, null=True, size=None),
        ),
    ]
