# Generated by Django 3.2.13 on 2025-01-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_auto_20230731_1014'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(fields=['post', 'ipaddress'], name='post_views_post_id_49dd7e_idx'),
        ),
    ]
