# Generated by Django 5.1.7 on 2025-04-15 10:46
from datetime import datetime, timezone

from django.db import migrations, models

from club.settings import MODERATOR_USERNAME, DELETED_USERNAME
from utils.strings import random_string

DOCS = [
    {
        "slug": "blocked_dolor",
        "type": "docs",
        "title": "💰 Как платить за Клуб из России и Беларуси",
        "text": "WRITE ME",
        "is_visible": True,
        "is_visible_in_feeds": False,
        "is_approved_by_moderator": False,
        "is_public": True,
    },
    {
        "slug": "contact",
        "type": "docs",
        "title": "📞 Связь с Клубом",
        "text": "WRITE ME",
        "is_visible": True,
        "is_visible_in_feeds": False,
        "is_approved_by_moderator": False,
        "is_public": True,
    },
    {
        "slug": "privacy_policy",
        "type": "docs",
        "title": "Политика Приватности",
        "text": "WRITE ME",
        "is_visible": True,
        "is_visible_in_feeds": False,
        "is_approved_by_moderator": False,
        "is_public": True,
    },
    {
        "slug": "about",
        "type": "docs",
        "title": "О Клубе 🎩",
        "text": "WRITE ME",
        "is_visible": True,
        "is_visible_in_feeds": False,
        "is_approved_by_moderator": False,
        "is_public": True,
    },
]

now = datetime.now(timezone.utc)


def create_moderator_user(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.get_or_create(
        slug=MODERATOR_USERNAME,
        defaults=dict(
            email="moderator@vas3k.club",
            secret_hash=random_string(length=20),
            membership_platform_type="direct",
            full_name="Модератор",
            company="Вастрик.Клуб",
            position="Бдю",
            city="Берлин",
            country="Германия",
            membership_started_at=now,
            membership_expires_at=now,
            created_at=now,
            updated_at=now,
            is_email_unsubscribed=True,
            moderation_status="approved",
            roles=["moderator"],
        ),
    )


def create_deleted_user(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.get_or_create(
        slug=DELETED_USERNAME,
        defaults=dict(
            email="deleted@vas3k.club",
            secret_hash=random_string(length=20),
            membership_platform_type="direct",
            full_name="💀 Юзер-зомби",
            company="[object Object]",
            position="None",
            city=None,
            country="Россия",
            membership_started_at=now,
            membership_expires_at=now,
            created_at=now,
            updated_at=now,
            is_email_unsubscribed=True,
            moderation_status="approved",
        ),
    )


def insert_main_docs(apps, schema_editor):
    User = apps.get_model("users", "User")
    Post = apps.get_model("posts", "Post")

    author = User.objects.filter(slug=MODERATOR_USERNAME).first()
    if not author:
        return

    for doc in DOCS:
        Post.objects.get_or_create(
            slug=doc["slug"],
            defaults={
                "type": doc["type"],
                "title": doc["title"],
                "text": doc["text"],
                "author": author,
                "created_at": now,
                "updated_at": now,
                "last_activity_at": now,
                "published_at": now,
                "is_visible": doc["is_visible"],
                "is_visible_in_feeds": doc["is_visible_in_feeds"],
                "is_commentable": False,
                "is_approved_by_moderator": True,
                "is_public": doc["is_public"],
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0028_postview_post_views_post_id_49dd7e_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpost',
            name='type',
            field=models.CharField(
                choices=[('post', 'Текст'), ('intro', '#intro'), ('link', 'Ссылка'), ('question', 'Вопрос'),
                         ('idea', 'Идея'), ('project', 'Проект'), ('event', 'Событие'), ('battle', 'Батл'),
                         ('weekly_digest', 'Журнал Клуба'), ('guide', 'Путеводитель'), ('thread', 'Тред'),
                         ('docs', 'Доки')], db_index=True, default='post', max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(
                choices=[('post', 'Текст'), ('intro', '#intro'), ('link', 'Ссылка'), ('question', 'Вопрос'),
                         ('idea', 'Идея'), ('project', 'Проект'), ('event', 'Событие'), ('battle', 'Батл'),
                         ('weekly_digest', 'Журнал Клуба'), ('guide', 'Путеводитель'), ('thread', 'Тред'),
                         ('docs', 'Доки')], db_index=True, default='post', max_length=32),
        ),
        migrations.RunPython(create_moderator_user),
        migrations.RunPython(create_deleted_user),
        migrations.RunPython(insert_main_docs),
    ]
