# Generated by Django 5.1.9 on 2025-06-16 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_alter_historicalpost_type_alter_post_type'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                UPDATE posts
                SET metadata = jsonb_set(
                    metadata,
                    '{event}',
                    jsonb_set(
                        COALESCE(metadata->'event', '{}'::jsonb),
                        '{participants}',
                        (
                            SELECT jsonb_agg(user_id)
                            FROM post_subscriptions
                            WHERE post_id = posts.id
                        ),
                        true
                    ),
                    true
                )
                WHERE type = 'event'
                  AND EXISTS (
                      SELECT 1 FROM post_subscriptions WHERE post_id = posts.id
                  );
            """,
            reverse_sql="""
                UPDATE posts
                SET metadata = jsonb_set(
                    metadata,
                    '{event}',
                    (metadata->'event') - 'participants'::text,
                    true
                )
                WHERE metadata->'event' ? 'participants';
            """
        )
    ]
