# Generated by Django 5.1.9 on 2025-07-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_migrate_event_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkedpost',
            options={'ordering': ['-created_at']},
        ),
    ]
