# Generated by Django 5.1.9 on 2025-07-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_alter_linkedpost_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpost',
            name='is_visible',
        ),
        migrations.AddField(
            model_name='post',
            name='moderation_status',
            field=models.CharField(choices=[('pending', '🕓 Пост на модерации'), ('approved', '👍 Хороший пост'), ('forgiven', '☹️ Пост не одобрен, но оставлен на сайте'), ('rejected', '❌ Пост отклонен модератором')], default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('draft', 'Черновик'), ('link_only', 'Только по ссылке'), ('everywhere', 'Виден везде')], db_index=True, default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='post',
            name='is_room_only',
            field=models.BooleanField(default=False),
        ),
    ]
