# Generated by Django 5.1.9 on 2025-07-25 07:35

from django.db import migrations
from django.db.models import Q


def set_moderation_status(apps, schema_editor):
    Post = apps.get_model('posts', 'Post')
    Post.objects.filter(is_approved_by_moderator=True).update(moderation_status='approved')
    Post.objects.filter(is_approved_by_moderator=False, is_visible=True).update(moderation_status='forgiven')


def reverse_moderation_status(apps, schema_editor):
    Post = apps.get_model('posts', 'Post')
    Post.objects.filter(moderation_status='approved').update(is_approved_by_moderator=True)


def set_visibility(apps, schema_editor):
    Post = apps.get_model('posts', 'Post')
    Post.objects.filter(is_visible=True).update(visibility='everywhere')
    Post.objects.filter(Q(is_visible=False) | Q(deleted_at__isnull=False)).update(visibility='draft')
    Post.objects.filter(is_shadow_banned=True).update(visibility='link_only')
    Post.objects.filter(is_visible=True, is_visible_in_feeds=False, room_id__isnull=True).update(visibility='link_only')
    Post.objects.filter(is_visible=True, is_visible_in_feeds=False, room_id__isnull=False).update(is_room_only=True)


def reverse_visibility(apps, schema_editor):
    Post = apps.get_model('posts', 'Post')

    # Reset all visibility-related flags
    Post.objects.update(
        is_visible=False,
        is_shadow_banned=False,
        is_visible_in_feeds=True,
    )

    # everywhere → visible
    Post.objects.filter(visibility='everywhere').update(is_visible=True)

    # draft → not visible (already set)

    # link_only → visible but shadow banned or not visible in feeds
    Post.objects.filter(visibility='link_only', room_id__isnull=True).update(
        is_shadow_banned=False,
        is_visible_in_feeds=False
    )
    Post.objects.filter(visibility='link_only', room_id__isnull=False).update(
        is_shadow_banned=True,
        is_visible_in_feeds=True
    )

    # is_room_only → visible not in feeds
    Post.objects.filter(is_room_only=True).update(
        is_visible_in_feeds=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_remove_historicalpost_is_visible_and_more'),
    ]

    operations = [
        migrations.RunPython(set_moderation_status, reverse_code=reverse_moderation_status),
        migrations.RunPython(set_visibility, reverse_code=reverse_visibility),
    ]
