# Generated by Django 5.1.9 on 2025-07-25 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_auto_20250725_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_visible_in_feeds',
        ),
    ]
