# Generated by Django 5.1.9 on 2025-07-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_remove_post_is_visible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_approved_by_moderator',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_shadow_banned',
        ),
    ]
