# Generated by Django 5.1.9 on 2025-07-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0035_remove_post_is_approved_by_moderator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='moderation_status',
            field=models.CharField(choices=[('none', '✍️ Еще не был на модерации'), ('pending', '🕓 Пост на модерации'), ('approved', '👍 Хороший пост'), ('forgiven', '☹️ Пост не одобрен, но оставлен на сайте'), ('rejected', '❌ Пост отклонен модератором')], default='none', max_length=12),
        ),
        migrations.RunSQL("update posts set moderation_status='none' where moderation_status = 'pending' and visibility = 'draft'"),
    ]
