# Generated by Django 6.0.7 on 2026-09-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_alter_post_moderation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpost',
            name='type',
            field=models.CharField(choices=[('post', 'Текст'), ('intro', '#intro'), ('link', 'Ссылка'), ('question', 'Вопрос'), ('project', 'Проект'), ('event', 'Событие'), ('battle', 'Батл'), ('weekly_digest', 'Журнал Клуба'), ('guide', 'Путеводитель'), ('thread', 'Тред'), ('docs', 'Доки'), ('request', 'Хочу пост про')], db_index=True, default='post', max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('post', 'Текст'), ('intro', '#intro'), ('link', 'Ссылка'), ('question', 'Вопрос'), ('project', 'Проект'), ('event', 'Событие'), ('battle', 'Батл'), ('weekly_digest', 'Журнал Клуба'), ('guide', 'Путеводитель'), ('thread', 'Тред'), ('docs', 'Доки'), ('request', 'Хочу пост про')], db_index=True, default='post', max_length=32),
        ),
    ]
