# Generated by Django 3.0.4 on 2020-07-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
