# Generated by Django 3.0.4 on 2020-07-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('started', 'started'), ('failed', 'failed'), ('success', 'success')], default='started', max_length=32),
        ),
    ]
