# Generated by Django 3.0.4 on 2020-07-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20200712_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
