# Generated by Django 5.1.9 on 2025-07-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postbookmark',
            options={'ordering': ['-created_at']},
        ),
    ]
