# Generated by Django 3.0.4 on 2020-04-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200408_1516'),
    ]

    operations = [
    ]
