# Generated by Django 3.0.4 on 2020-04-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200409_0846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['group', 'index']},
        ),
    ]
