# Generated by Django 3.0.4 on 2020-04-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200416_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_unsubscribed',
            field=models.BooleanField(default=False),
        ),
    ]
