# Generated by Django 3.0.4 on 2020-05-21 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200519_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geo',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='geo_id',
        ),
        migrations.AddField(
            model_name='user',
            name='geo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Geo'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='group',
            field=models.CharField(choices=[('personal', 'О себе'), ('tech', 'Технологии'), ('club', 'В Клубе я...'), ('hobbies', 'Хобби'), ('other', 'Остальное')], default='other', max_length=32),
        ),
    ]
