# Generated by Django 3.0.4 on 2020-05-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='group',
            field=models.CharField(choices=[('personal', 'О себе'), ('tech', 'Технологии'), ('club', 'Для других членов Клуба я...'), ('hobbies', 'Хобби'), ('other', 'Остальное')], default='other', max_length=32),
        ),
    ]
