# Generated by Django 3.0.4 on 2020-05-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_contact'),
    ]

    operations = [
    ]
