# Generated by Django 3.0.4 on 2020-05-26 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200523_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('image', models.URLField()),
                ('description', models.TextField()),
                ('style', models.CharField(default='', max_length=256, null=True)),
                ('index', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'achievements',
                'ordering': ['index'],
            },
        ),
        migrations.AddField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.Achievement'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('achievement', 'user')},
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='style',
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='type',
        ),
    ]
