# Generated by Django 3.0.4 on 2020-06-02 11:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0011_auto_20200526_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='membership_type',
        ),
        migrations.AddField(
            model_name='user',
            name='moderation_status',
            field=models.CharField(choices=[('intro', 'intro'), ('on_review', 'on_review'), ('rejected', 'rejected'),
                                            ('approved', 'approved')], default='intro', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(
                choices=[('curator', 'Куратор'), ('moderator', 'Модератор'), ('god', 'Бог')], max_length=32),
                                                            default=list, size=None),
        ),
        migrations.RunSQL("""
            update users set moderation_status = 'approved'
            where is_profile_complete = true
            and is_profile_reviewed = true
            and is_profile_rejected = false
        """),
        migrations.RunSQL("""
            update users set moderation_status = 'rejected'
            where is_profile_complete = true
            and is_profile_reviewed = true
            and is_profile_rejected = true
        """),
        migrations.RunSQL("""
            update users set moderation_status = 'on_review'
            where is_profile_complete = true
            and is_profile_reviewed = false
            and is_profile_rejected = false
        """),
    ]
