# Generated by Django 3.0.4 on 2020-06-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200602_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_profile_complete',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_profile_rejected',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_profile_reviewed',
        ),
        migrations.AlterField(
            model_name='user',
            name='moderation_status',
            field=models.CharField(choices=[('intro', 'intro'), ('on_review', 'on_review'), ('rejected', 'rejected'), ('approved', 'approved')], db_index=True, default='intro', max_length=32),
        ),
    ]
