# Generated by Django 3.0.4 on 2020-06-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200602_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='group',
            field=models.CharField(choices=[('personal', 'О себе'), ('tech', 'Технологии'), ('club', 'Для других членов Клуба я...'), ('hobbies', 'Хобби'), ('other', 'Остальное'), ('care', 'Волнует')], default='other', max_length=32),
        ),
    ]
