# Generated by Django 3.0.4 on 2020-07-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200602_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membership_platform_type',
            field=models.CharField(choices=[('direct', 'Direct'), ('patreon', 'Patreon')], default='patreon', max_length=128),
        ),
    ]
