# Generated by Django 3.0.4 on 2020-07-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200710_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membership_platform_id',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
