# Generated by Django 3.0.4 on 2020-07-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200712_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='membership_platform_id',
            new_name='patreon_id',
        ),
    ]
