# Generated by Django 3.1 on 2020-08-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hat',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership_platform_data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_data',
            field=models.JSONField(null=True),
        ),
    ]
