# Generated by Django 3.2 on 2021-05-12 10:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200822_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='moderation_status',
            field=models.CharField(choices=[('intro', 'intro'), ('on_review', 'on_review'), ('rejected', 'rejected'), ('approved', 'approved'), ('deleted', 'deleted')], db_index=True, default='intro', max_length=32),
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_subscribed_to_posts', models.BooleanField(default=True)),
                ('is_subscribed_to_comments', models.BooleanField(default=True)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_from', to='users.user')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_to', to='users.user')),
            ],
            options={
                'db_table': 'friends',
                'unique_together': {('user_from', 'user_to')},
            },
        ),
    ]
