# Generated by Django 3.2 on 2021-06-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210512_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret_hash',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
