# Generated by Django 3.2.8 on 2021-11-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_user_secret_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='moderation_notes',
            field=models.TextField(null=True),
        ),
    ]
