# Generated by Django 3.2.8 on 2021-12-22 20:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_user_secret_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muted',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_from', to='users.user')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_to', to='users.user')),
            ],
            options={
                'db_table': 'muted',
                'unique_together': {('user_from', 'user_to')},
            },
        ),
    ]
