# Generated by Django 3.2.13 on 2024-05-16 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20230808_1201'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userexpertise',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userexpertise',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserExpertise',
        ),
    ]
