# Generated by Django 5.1.5 on 2025-02-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20250111_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='custom_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
