# Generated by Django 5.1.7 on 2025-04-14 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_add_achievement_custom_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Muted',
            new_name='UserMuted',
        ),
    ]
