# Generated by Django 5.1.9 on 2025-07-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_rename_muted_usermuted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userachievement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='usermuted',
            options={'ordering': ['-created_at']},
        ),
    ]
