# Generated by Django 5.1.13 on 2026-05-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_friend_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referer',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
