# Generated by Django 3.2.13 on 2023-07-31 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misc', '0003_alter_networkitem_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('slug', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=64)),
                ('subtitle', models.CharField(blank=True, max_length=256, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('icon', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(max_length=16)),
                ('style', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('chat_name', models.CharField(blank=True, max_length=128, null=True)),
                ('chat_url', models.URLField(blank=True, null=True)),
                ('chat_id', models.CharField(blank=True, max_length=32, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now_add=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_bot_active', models.BooleanField(default=True)),
                ('index', models.PositiveIntegerField(default=0)),
                ('network_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='misc.networkgroup')),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['-last_activity_at'],
            },
        ),
    ]
