# Generated by Django 3.2.13 on 2023-07-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['index']},
        ),
        migrations.AddField(
            model_name='room',
            name='is_open_for_posting',
            field=models.BooleanField(default=True),
        ),
    ]
