# Generated by Django 3.2.13 on 2023-09-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20230731_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='is_bot_active',
            new_name='send_new_posts_to_chat',
        ),
        migrations.AddField(
            model_name='room',
            name='send_new_comments_to_chat',
            field=models.BooleanField(default=False),
        ),
    ]
