# Generated by Django 3.2.13 on 2024-11-11 18:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20230925_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_subscriptions', to='users.user')),
            ],
            options={
                'db_table': 'room_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='RoomMuted',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_users', to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_room', to='users.user')),
            ],
            options={
                'db_table': 'room_muted',
                'unique_together': {('user', 'room')},
            },
        ),
    ]
