# Generated by Django 5.1.5 on 2025-03-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_roommuted_roomsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='chat_member_count',
            field=models.IntegerField(default=0),
        ),
    ]
