# Generated by Django 5.1.9 on 2025-07-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_chat_member_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='icon',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
