import os

DAILY_QUESTION_LIMIT = 2
QUESTION_TITLE_MAX_LEN = 150
QUESTION_BODY_MAX_LEN = 2500

TELEGRAM_ADMIN_BOT_ID = 777000
TELEGRAM_HELP_DESK_BOT_TOKEN = os.getenv("TELEGRAM_HELP_DESK_BOT_TOKEN")
TELEGRAM_HELP_DESK_BOT_QUESTION_CHANNEL_ID = os.getenv("TELEGRAM_HELP_DESK_BOT_QUESTION_CHANNEL_ID")
TELEGRAM_HELP_DESK_BOT_QUESTION_CHANNEL_DISCUSSION_ID = os.getenv("TELEGRAM_HELP_DESK_BOT_QUESTION_CHANNEL_DISCUSSION_ID")
TELEGRAM_HELP_DESK_BOT_WEBHOOK_URL = "https://vas3k.club/telegram/helpdeskbot/webhook/"
TELEGRAM_HELP_DESK_BOT_WEBHOOK_HOST = "0.0.0.0"
TELEGRAM_HELP_DESK_BOT_WEBHOOK_PORT = 8817
