# Generated by Django 3.1 on 2020-08-09 16:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0019_auto_20200809_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRequests',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('archive', 'archive'), ('forget', 'forget')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_requests', to='users.user')),
            ],
            options={
                'db_table': 'data_requests',
            },
        ),
    ]
