# Generated by Django 6.0.7 on 2026-09-15 08:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0035_user_referer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapMessages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_messages', to='users.user')),
            ],
            options={
                'db_table': 'map_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
