# Generated by Django 6.0.7 on 2026-09-15 09:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_move_geo_from_users'),
        ('users', '0036_move_geo_to_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmessages',
            name='upvotes',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.CreateModel(
            name='MapMessageVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ipaddress', models.GenericIPAddressField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='map.mapmessages')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_message_votes', to='users.user')),
            ],
            options={
                'db_table': 'map_message_votes',
                'unique_together': {('user', 'message')},
            },
        ),
    ]
