# Generated by Django 3.0.4 on 2020-04-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GodSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest_intro', models.TextField(null=True)),
            ],
            options={
                'db_table': 'god_settings',
            },
        ),
    ]
