# Generated by Django 3.0.4 on 2020-07-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='godsettings',
            name='network_page',
            field=models.TextField(null=True),
        ),
    ]
