# Generated by Django 3.2 on 2021-08-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_godsettings_network_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='godsettings',
            name='digest_title',
            field=models.TextField(null=True),
        ),
    ]
