# Generated by Django 3.2.13 on 2023-02-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20210829_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='godsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
