# Generated by Django 5.1.9 on 2025-06-26 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_alter_godsettings_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GodSettings',
        ),
    ]
