# Generated by Django 3.0.4 on 2020-04-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='deleted_by',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcomment',
            name='deleted_by',
            field=models.UUIDField(null=True),
        ),
    ]
