# Generated by Django 3.0.4 on 2020-04-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20200420_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentvote',
            name='ipaddress',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='commentvote',
            name='useragent',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
