# Generated by Django 3.0.4 on 2020-04-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20200421_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='historicalcomment',
            name='title',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
