# Generated by Django 3.1 on 2020-08-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20200809_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='url',
            field=models.URLField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='url',
            field=models.URLField(max_length=1024, null=True),
        ),
    ]
