# Generated by Django 3.2 on 2021-09-11 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_auto_20200822_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentvote',
            name='useragent',
        ),
        migrations.RemoveField(
            model_name='historicalcomment',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='historicalcomment',
            name='is_pinned',
        ),
        migrations.RemoveField(
            model_name='historicalcomment',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='historicalcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='historicalcomment',
            name='reply_to',
        ),
    ]
