# Generated by Django 3.1 on 2020-10-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0002_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apps',
            name='app_key',
        ),
        migrations.RemoveField(
            model_name='apps',
            name='secret_key',
        ),
        migrations.AddField(
            model_name='apps',
            name='jwt_algorithm',
            field=models.CharField(default='HS256', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apps',
            name='jwt_expire_hours',
            field=models.IntegerField(default=240),
        ),
        migrations.AddField(
            model_name='apps',
            name='jwt_secret',
            field=models.CharField(default='secret', max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apps',
            name='id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
