# Generated by Django 3.2 on 2021-06-13 13:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0003_auto_20201024_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='jwt_secret',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='apps',
            name='redirect_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=list, size=None),
        ),
    ]
