# Generated by Django 3.2 on 2021-06-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0004_auto_20210613_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='jwt_secret',
            field=models.TextField(),
        ),
    ]
