# Generated by Django 3.2.13 on 2022-05-25 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_user_membership_platform_type'),
        ('authn', '0005_alter_apps_jwt_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='apps', to='users.user'),
        ),
        migrations.AddField(
            model_name='apps',
            name='service_token',
            field=models.CharField(db_index=True, max_length=128, null=True, unique=True),
        ),
    ]
