# Generated by Django 3.2.13 on 2023-09-25 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0008_auto_20230306_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='app',
        ),
        migrations.DeleteModel(
            name='Apps',
        ),
    ]
