# Generated by Django 6.0.7 on 2026-08-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0009_auto_20230925_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='ipaddress',
            field=models.GenericIPAddressField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='code',
            name='useragent',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
