# Generated by Django 6.0.7 on 2026-08-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0010_code_ipaddress_useragent'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ipaddress',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='useragent',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
