# Generated by Django 5.1.7 on 2025-04-14 08:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('group', models.CharField(choices=[('personal', 'Я'), ('tech', 'Технологии'), ('club', 'Для других членов Клуба я...'), ('hobbies', 'Хобби'), ('collectible', 'Коллекционные теги'), ('other', 'Другие')], default='other', max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('index', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['-group', 'index'],
            },
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tags', to='tags.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='users.user')),
            ],
            options={
                'db_table': 'user_tags',
                'unique_together': {('tag', 'user')},
            },
        ),
    ]
