# Generated by Django 5.1.9 on 2025-07-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertag',
            options={'ordering': ['-created_at']},
        ),
    ]
