# Generated by Django 3.2.13 on 2023-02-28 08:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkGroup',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('text', models.TextField(blank=True, null=True)),
                ('index', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'network_groups',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='NetworkItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('image', models.URLField()),
                ('icon', models.CharField(blank=True, max_length=256, null=True)),
                ('url', models.URLField()),
                ('telegram_chat_id', models.CharField(blank=True, max_length=32, null=True)),
                ('index', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='misc.networkgroup')),
            ],
            options={
                'db_table': 'network_items',
                'ordering': ['index'],
            },
        ),
    ]
