# Generated by Django 3.2.13 on 2023-03-18 20:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_networkgroup_networkitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkitem',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=32, primary_key=True, serialize=False),
        ),
    ]
