# Generated by Django 3.2.13 on 2023-07-31 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_alter_networkitem_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetworkItem',
        ),
    ]
