# Generated by Django 5.1.13 on 2025-10-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0004_delete_networkitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkgroup',
            name='custom_template',
            field=models.CharField(choices=[('block', 'block'), ('services', 'services'), ('top', 'top'), ('title', 'title'), ('other', 'other')], default='block', max_length=16),
        ),
    ]
