# Generated by Django 5.1.9 on 2025-06-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest_title', models.TextField(null=True)),
                ('digest_intro', models.TextField(null=True)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
    ]
