# Generated by Django 5.1.9 on 2025-07-21 08:38

from django.db import migrations, models

def create_initial_settings(apps, schema_editor):
    ClubSettings = apps.get_model('godmode', 'ClubSettings')

    ClubSettings.objects.update_or_create(
        code='digest_title',
        defaults={'value': None}
    )

    ClubSettings.objects.update_or_create(
        code='digest_intro',
        defaults={'value': None}
    )

    ClubSettings.objects.update_or_create(
        code='app_name',
        defaults={'value': "Вастрик.Клуб"}
    )

    ClubSettings.objects.update_or_create(
        code='app_title',
        defaults={'value': "Вастрик.Клуб 🤘✖️👩‍💻"}
    )

    ClubSettings.objects.update_or_create(
        code='app_description',
        defaults={'value': "Всё интересное происходит за закрытыми дверями"}
    )


class Migration(migrations.Migration):

    dependencies = [
        ('godmode', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("delete from settings"),
        migrations.RemoveField(
            model_name='clubsettings',
            name='digest_intro',
        ),
        migrations.RemoveField(
            model_name='clubsettings',
            name='digest_title',
        ),
        migrations.RemoveField(
            model_name='clubsettings',
            name='id',
        ),
        migrations.AddField(
            model_name='clubsettings',
            name='code',
            field=models.CharField(default='digest_title', max_length=32, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubsettings',
            name='value',
            field=models.TextField(null=True),
        ),
        migrations.RunPython(create_initial_settings),
    ]
