name: 'Send message to Telegram'
description: 'Action for send message in Telegram'
inputs:
  text:
    description: 'The message that will be sent to telegram.'
    required: true
  chat_id:
    description: 'Chat id'
    required: false
    default: ${{ secrets.CI_CHAT_ID }}
  bot_token:
    description: 'Bot token'
    required: false
    default: ${{ secrets.CI_BOT_TOKEN }}
runs:
  using: "docker"
  image: "Dockerfile"
