name: 'Send message to Telegram'
inputs:
  token:
    description: "Token bot"
    required: true
  text:
    description: 'The message that will be sent to telegram.'
    required: true
  chat_id:
    description: 'Chat id'
    required: false
    default: "-1001287599988"
description: 'Action for send message in Telegram'
runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/send_message.sh ${{ inputs.token }} ${{ inputs.chat_id }} "${{ inputs.text }}"
      shell: bash
