# Generated by Django 3.0.4 on 2020-05-02 14:14

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0009_auto_20200429_0817'),
        ('users', '0006_user_is_email_unsubscribed'),
        ('comments', '0005_auto_20200424_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', django.contrib.postgres.search.SearchVectorField(editable=False)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='index', to='comments.Comment')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='index', to='posts.Post')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='index', to='users.User')),
            ],
            options={
                'db_table': 'search_index',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='searchindex',
            index=django.contrib.postgres.indexes.GinIndex(fastupdate=False, fields=['index'], name='search_inde_index_c69d39_gin'),
        ),
    ]
