# Generated by Django 3.2.13 on 2022-06-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20200902_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchindex',
            name='created_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
