# Generated by Django 3.2.13 on 2026-07-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0004_alter_searchindex_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchindex",
            name="author",
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="searchindex",
            name="upvotes",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="searchindex",
            name="title",
            field=models.TextField(null=True),
        ),
    ]
