# Generated by Django 5.1.5 on 2025-03-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tickets_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='session',
            field=models.JSONField(default=dict),
        ),
    ]
