# Generated by Django 5.1.5 on 2025-03-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_tickets_sold_ticketsale_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='email_template',
            new_name='send_email_title',
        ),
        migrations.AddField(
            model_name='ticket',
            name='send_email_markdown',
            field=models.TextField(blank=True, null=True),
        ),
    ]
