# Generated by Django 5.1.7 on 2025-04-14 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0002_auto_20241227_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='invited_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_invite', to='users.user'),
        ),
    ]
