# Generated by Django 5.1.9 on 2025-07-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0003_alter_invite_invited_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invite',
            options={'ordering': ['-created_at']},
        ),
    ]
