# Generated by Django 3.2 on 2021-04-07 15:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('email_bounce', 'email_bounce'), ('email_complaint', 'email_complaint')], max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.CharField(max_length=128, null=True)),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'webhook_events',
            },
        ),
    ]
