name: PR-Security-Check

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    check_secret:
        name: Check Secrets
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v
            with:
                fetch-depth: 0
          
          - name: GitLeaks
            uses: gitleaks/gitleaks-action@v2
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    