# Generated by Django 5.1.5 on 2025-02-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_alter_badge_options'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO "badges"("code","created_at","title","description","price_days","is_visible")
            VALUES
            ('thanks','2025-02-16 11:37:53.514167+02','Спасибо!','',30,TRUE);
        """)
    ]
