# Generated by Django 5.1.9 on 2025-07-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0004_auto_20250216_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbadge',
            options={'ordering': ['-created_at']},
        ),
    ]
